In [18]:
import pandas as pd
import numpy as np
import tensorflow as tf #imports

In [3]:
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "-1"
import tensorflow as tf
print("Dispositivos encontrados:", tf.config.list_physical_devices()) #tive q fazer isso pois o fit nao estava funcionando

Dispositivos encontrados: [PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

E0000 00:00:1779588185.509465  570531 cuda_platform.cc:52] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
I0000 00:00:1779588185.509488  570531 cuda_diagnostics.cc:160] env: CUDA_VISIBLE_DEVICES="-1"
I0000 00:00:1779588185.509496  570531 cuda_diagnostics.cc:163] CUDA_VISIBLE_DEVICES is set to -1 - this hides all GPUs from CUDA
I0000 00:00:1779588185.509502  570531 cuda_diagnostics.cc:171] verbose logging is disabled. Rerun with verbose logging (usually --v=1 or --vmodule=cuda_diagnostics=1) to get more diagnostic output from this module
I0000 00:00:1779588185.509503  570531 cuda_diagnostics.cc:176] retrieving CUDA diagnostic information for host: fedora
I0000 00:00:1779588185.509505  570531 cuda_diagnostics.cc:183] hostname: fedora
I0000 00:00:1779588185.509640  570531 cuda_diagnostics.cc:190] libcuda reported version is: 580.159.3
I0000 00:00:1779588185.509653  570531 cuda_diagnostics.cc:194] kernel reported version is: 580.159.3
I0000 00:00:1779588185.509654  570531 cuda_diagnostics.cc:284] kernel version seems to match DSO: 580.159.3

In [4]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, InputLayer, Dropout #imports

In [5]:
X = pd.read_csv('entradas_breast.csv')
y=  pd.read_csv('saidas_breast.csv') #dados

In [6]:
classificador = Sequential()
classificador.add(InputLayer(shape=(30,)))
classificador.add(Dense(units=16, activation='relu', kernel_initializer='random_uniform'))
classificador.add(Dropout(0.2))
classificador.add(Dense(units=16, activation='relu', kernel_initializer='random_uniform'))
classificador.add(Dropout(0.2))
classificador.add(Dense(units=1, activation='sigmoid')) #classificador e as camadas dele

In [7]:
classificador.compile(optimizer='adam', loss='binary_crossentropy', metrics=['binary_accuracy']) #compila

In [8]:
classificador.fit(X, y, batch_size = 10, epochs = 100) #treinando

Epoch 1/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 819us/step - binary_accuracy: 0.5747 - loss: 1.1464
Epoch 2/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 809us/step - binary_accuracy: 0.6151 - loss: 0.5684
Epoch 3/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 726us/step - binary_accuracy: 0.6573 - loss: 0.5367
Epoch 4/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 928us/step - binary_accuracy: 0.6801 - loss: 0.5152
Epoch 5/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 804us/step - binary_accuracy: 0.7223 - loss: 0.4965
Epoch 6/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 785us/step - binary_accuracy: 0.7346 - loss: 0.4938
Epoch 7/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.7627 - loss: 0.4714
Epoch 8/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 873us/step - binary_accuracy: 0.7873 - loss: 0.4496
Epoch 9/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 688us/step - binary_accuracy: 0.7979 - loss: 0.4561
Epoch 10/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 715us/step - binary_accuracy: 0.8049 - loss: 0.4413
Epoch 11/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 695us/step - binary_accuracy: 0.8049 - loss: 0.4283
Epoch 12/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 681us/step - binary_accuracy: 0.8383 - loss: 0.3887
Epoch 13/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 822us/step - binary_accuracy: 0.8383 - loss: 0.3975
Epoch 14/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 729us/step - binary_accuracy: 0.8576 - loss: 0.3661
Epoch 15/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 691us/step - binary_accuracy: 0.8594 - loss: 0.3663
Epoch 16/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 746us/step - binary_accuracy: 0.8629 - loss: 0.3327
Epoch 17/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 731us/step - binary_accuracy: 0.8664 - loss: 0.3490
Epoch 18/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 700us/step - binary_accuracy: 0.8541 - loss: 0.3463
Epoch 19/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 805us/step - binary_accuracy: 0.8875 - loss: 0.3195
Epoch 20/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 819us/step - binary_accuracy: 0.8963 - loss: 0.2946
Epoch 21/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 718us/step - binary_accuracy: 0.8752 - loss: 0.3060
Epoch 22/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 696us/step - binary_accuracy: 0.8717 - loss: 0.3099
Epoch 23/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 719us/step - binary_accuracy: 0.8770 - loss: 0.3198
Epoch 24/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 686us/step - binary_accuracy: 0.8858 - loss: 0.2988
Epoch 25/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 727us/step - binary_accuracy: 0.8963 - loss: 0.2665
Epoch 26/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 746us/step - binary_accuracy: 0.8910 - loss: 0.2894
Epoch 27/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 723us/step - binary_accuracy: 0.8963 - loss: 0.2637
Epoch 28/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 750us/step - binary_accuracy: 0.8963 - loss: 0.2503
Epoch 29/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 753us/step - binary_accuracy: 0.8928 - loss: 0.2667
Epoch 30/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 880us/step - binary_accuracy: 0.9086 - loss: 0.2505
Epoch 31/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 685us/step - binary_accuracy: 0.8928 - loss: 0.2873
Epoch 32/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 738us/step - binary_accuracy: 0.8946 - loss: 0.2758
Epoch 33/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 882us/step - binary_accuracy: 0.8910 - loss: 0.2625
Epoch 34/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 896us/step - binary_accuracy: 0.9033 - loss: 0.2460
Epoch 35/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 733us/step - binary_accuracy: 0.9016 - loss: 0.2414
Epoch 36/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 757us/step - binary_accuracy: 0.9104 - loss: 0.2283
Epoch 37/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 880us/step - binary_accuracy: 0.9051 - loss: 0.2288
Epoch 38/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 772us/step - binary_accuracy: 0.9069 - loss: 0.2359
Epoch 39/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 693us/step - binary_accuracy: 0.9121 - loss: 0.2460
Epoch 40/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 821us/step - binary_accuracy: 0.9086 - loss: 0.2409
Epoch 41/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 823us/step - binary_accuracy: 0.9069 - loss: 0.2217
Epoch 42/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 926us/step - binary_accuracy: 0.9227 - loss: 0.2315
Epoch 43/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - binary_accuracy: 0.9069 - loss: 0.2220
Epoch 44/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 824us/step - binary_accuracy: 0.9069 - loss: 0.2224
Epoch 45/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 766us/step - binary_accuracy: 0.8946 - loss: 0.2501
Epoch 46/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 828us/step - binary_accuracy: 0.9069 - loss: 0.2406
Epoch 47/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 789us/step - binary_accuracy: 0.9156 - loss: 0.2152
Epoch 48/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 883us/step - binary_accuracy: 0.9139 - loss: 0.2369
Epoch 49/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 732us/step - binary_accuracy: 0.9051 - loss: 0.2287
Epoch 50/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 772us/step - binary_accuracy: 0.8893 - loss: 0.2610
Epoch 51/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 869us/step - binary_accuracy: 0.9209 - loss: 0.2047
Epoch 52/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 752us/step - binary_accuracy: 0.8946 - loss: 0.2420
Epoch 53/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 734us/step - binary_accuracy: 0.9069 - loss: 0.2420
Epoch 54/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9051 - loss: 0.2414
Epoch 55/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 691us/step - binary_accuracy: 0.9139 - loss: 0.2175
Epoch 56/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 935us/step - binary_accuracy: 0.9192 - loss: 0.2202
Epoch 57/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 767us/step - binary_accuracy: 0.9121 - loss: 0.2573
Epoch 58/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 793us/step - binary_accuracy: 0.9086 - loss: 0.2323
Epoch 59/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 700us/step - binary_accuracy: 0.9051 - loss: 0.2538
Epoch 60/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 738us/step - binary_accuracy: 0.9156 - loss: 0.2094
Epoch 61/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 715us/step - binary_accuracy: 0.9174 - loss: 0.2275
Epoch 62/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 857us/step - binary_accuracy: 0.9174 - loss: 0.2263
Epoch 63/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 740us/step - binary_accuracy: 0.9174 - loss: 0.2031
Epoch 64/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 876us/step - binary_accuracy: 0.9209 - loss: 0.2033
Epoch 65/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9016 - loss: 0.2587
Epoch 66/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 742us/step - binary_accuracy: 0.9227 - loss: 0.2142
Epoch 67/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 960us/step - binary_accuracy: 0.8998 - loss: 0.2418
Epoch 68/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 706us/step - binary_accuracy: 0.9139 - loss: 0.2374
Epoch 69/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 717us/step - binary_accuracy: 0.9016 - loss: 0.2334
Epoch 70/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 779us/step - binary_accuracy: 0.9174 - loss: 0.2334
Epoch 71/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 968us/step - binary_accuracy: 0.9156 - loss: 0.2013
Epoch 72/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 778us/step - binary_accuracy: 0.9192 - loss: 0.2155
Epoch 73/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 757us/step - binary_accuracy: 0.8981 - loss: 0.2694
Epoch 74/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 756us/step - binary_accuracy: 0.9086 - loss: 0.2332
Epoch 75/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 886us/step - binary_accuracy: 0.9104 - loss: 0.2226
Epoch 76/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 900us/step - binary_accuracy: 0.9174 - loss: 0.2095
Epoch 77/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 868us/step - binary_accuracy: 0.9033 - loss: 0.2471
Epoch 78/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 917us/step - binary_accuracy: 0.9209 - loss: 0.2036
Epoch 79/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 768us/step - binary_accuracy: 0.9069 - loss: 0.2393
Epoch 80/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 730us/step - binary_accuracy: 0.9033 - loss: 0.2401
Epoch 81/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 735us/step - binary_accuracy: 0.9121 - loss: 0.2203
Epoch 82/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 720us/step - binary_accuracy: 0.9209 - loss: 0.2096
Epoch 83/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 746us/step - binary_accuracy: 0.9174 - loss: 0.2140
Epoch 84/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 739us/step - binary_accuracy: 0.9121 - loss: 0.2363
Epoch 85/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 727us/step - binary_accuracy: 0.9174 - loss: 0.2097
Epoch 86/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 708us/step - binary_accuracy: 0.8928 - loss: 0.2712
Epoch 87/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 696us/step - binary_accuracy: 0.9139 - loss: 0.2201
Epoch 88/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 683us/step - binary_accuracy: 0.9121 - loss: 0.2303
Epoch 89/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 719us/step - binary_accuracy: 0.9174 - loss: 0.2435
Epoch 90/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 932us/step - binary_accuracy: 0.9069 - loss: 0.2328
Epoch 91/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 821us/step - binary_accuracy: 0.9209 - loss: 0.2104
Epoch 92/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 745us/step - binary_accuracy: 0.9139 - loss: 0.2296
Epoch 93/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9156 - loss: 0.2168
Epoch 94/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9174 - loss: 0.2120
Epoch 95/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 737us/step - binary_accuracy: 0.9156 - loss: 0.1953
Epoch 96/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 737us/step - binary_accuracy: 0.9174 - loss: 0.1943
Epoch 97/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - binary_accuracy: 0.8981 - loss: 0.2403
Epoch 98/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 851us/step - binary_accuracy: 0.9086 - loss: 0.2548
Epoch 99/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 926us/step - binary_accuracy: 0.9069 - loss: 0.2265
Epoch 100/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 957us/step - binary_accuracy: 0.9121 - loss: 0.2302

In [9]:
X #vendo X

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave_points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave_points_worst,symmetry_worst,fractal_dimension_worst
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,25.38,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,24.99,23.41,158.80,1956.0,0.12380,0.18660,0.2416,186.0000,275.0000,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,23.57,25.53,152.50,1709.0,0.14440,0.42450,0.4504,243.0000,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,14.91,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,173.00000
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,198.00000,0.10430,0.1809,0.05883,...,22.54,16.67,152.20,1575.0,0.13740,205.00000,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,111.00000,0.11590,0.24390,0.13890,0.1726,0.05623,...,25.45,26.40,166.10,2027.0,141.00000,0.21130,0.4107,0.2216,206.0000,0.07115
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,144.00000,0.09791,0.1752,0.05533,...,23.69,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,159.0000,0.05648,...,18.98,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,20.60,29.33,140.10,1265.0,0.11780,277.00000,0.35140,152.00000,0.2397,0.07016,...,25.74,39.42,184.60,1821.0,165.00000,0.86810,0.9387,265.0000,0.4087,124.00000
568,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,...,9456.00,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [10]:
y #vendo y

     0
0    0
1    0
2    0
3    0
4    0
..  ..
564  0
565  0
566  0
567  0
568  1

[569 rows x 1 columns]

In [11]:
novo = np.array([[15.80, 8.34, 118, 900, 0.10, 0.26, 0.08, 0.134, 0.178, 0.20, 0.05, 1098, 0.87, 4500, 145.2, 0.005, 0.04, 0.05, 0.015, 0.03,
0.007, 23.15, 16.64, 178.5, 2018, 0.14, 0.185, 0.84, 158, 0.363]]) #novo dado

In [12]:
novo.size #tamanho do novo dado

30

In [15]:
previsao = classificador.predict(novo) #fazendo a previsao pro novo dado

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step

In [16]:
previsao = previsao > 0.5
previsao #fazendo ficar True ou False

array([[ True]])

In [17]:
if previsao: #pra ver se e maligno ou nao
    print('Malígno')
else: 
    print('Benigno')

Malígno

# Salvar a rede

In [19]:
classificador.save('classificador_breast.keras') #salvando modelo

In [20]:
classificador_novo = tf.keras.models.load_model('classificador_breast.keras') #puxando o modelo salvo

In [22]:
classificador_novo.summary()  #vendo a rede em si

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 16)             │           496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 16)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 16)             │           272 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 16)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,357 (9.21 KB)

 Trainable params: 785 (3.07 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 1,572 (6.14 KB)

In [23]:
classificador_novo.predict(novo) #testando a rede salva

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step

array([[1.]], dtype=float32)